# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import operator
from pathlib import Path
from typing import Annotated

from pydantic import BaseModel, Field

from agent_hardener.models import DefenderInput, DefenderOutput


# --- Internal LangGraph State ---
class GraphState(BaseModel):
    # Inputs
    original_input: DefenderInput
    iteration_count: int = 0

    # Path to the run's active-state NeMo Relay plugin config (plugins.toml)
    relay_plugins_path: Path | None = None

    # Model that scores tool calls inside the victim; None takes the run's analysis default
    safety_llm: str | None = None

    # Cumulative configuration string (TOML)
    current_config: str = ""

    # Test Suite generated by Augmenter
    test_attacks: list[str] = Field(default_factory=list)
    test_benigns: list[str] = Field(default_factory=list)

    # Analysis from Analyzer
    vulnerability_analysis: str = ""

    # Generated string from Generator
    draft_instruction: str = ""

    # Turnaround/Retry loop
    retry_counter: int = 0
    # Use Annotated with operator.add so parallel nodes or loop iterations can append to the list safely
    feedback_log: Annotated[list[str], operator.add] = Field(default_factory=list)

    # Evaluation result
    eval_passed: bool = False

    # Final Output
    final_output: DefenderOutput | None = None
